[package]
name = "toy-crdt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
num_cpus = "1.13.1"
stateright = "0.29.0"

[patch.crates-io]
stateright = { git = "https://github.com/jeffa5/stateright", branch = "public-out" }

[profile.release]
debug = true
